on:
  workflow_call:
    inputs:
      version:
        description: 'The version number to use for the build'
        required: true
        type: string
      checkout-ref:
        description: 'The commit SHA to checkout'
        required: true
        type: string
  
jobs:
  build-app:
    runs-on: windows-latest
    steps:
    - name: Log Branch
      run: |
        echo "Branch: ${{ inputs.checkout-ref }}"
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout-ref }}
    - name: Setup .NET Core
      run: |
        Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
        .\dotnet-install.ps1 -Version 8.0.405 -Architecture x86
      shell: pwsh
    - name: Restore
      uses: cake-build/cake-action@v2
      with:
        target: Restore
    - name: Build
      uses: cake-build/cake-action@v2
      with:
        target: Build-Only
        arguments: |
          versionNumber: ${{inputs.version}}
    - name: Run tests
      uses: cake-build/cake-action@v2
      with:
        target: Test-Only
        arguments: |
          testFilter: Category!=LocalTest
    - name: Publish Unit Test Results
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      with:
        files: "**/TestResults/*.xml"